package com.tests.babygodzilla;

import static org.junit.Assert.*;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;

import org.junit.*;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NoAlertPresentException;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.safari.SafariDriver;
import org.openqa.selenium.safari.SafariOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.Assume;
import org.openqa.selenium.JavascriptExecutor;
import com.gargoylesoftware.htmlunit.javascript.background.JavaScriptExecutor;


public class SafariFullBabyGodzillaTest {
	private String baseUrl;
	private WebDriver driver = null;
	private boolean acceptNextAlert = true;
	private StringBuffer verificationErrors = new StringBuffer();
	private String adminUserName = "admin@fusetest.com";
	private String adminPassword = "test123";
	private String sheetName = "excel";
	private String email1 = "ram@dell.com";
	private String email2 = "sirouhi@yahoo.com";
	private String email3 = "anup@gmail.com";
	private String email4 = "sirouhi@gmail.com";
	private String email5 = "bob@bobmail.com";
	private String email6 = "bob@bobthebuilder.com";
	private String email7 = "jinaconven@bonanza.com";
	private String firstName1 = "anish";
	private String firstName2 = "Mary";
	private String lastName1 = "mulligan";
	private String lastName2 = "Goldman";
	//private String lastName3 = "mulligan";
	private String position1 = "Sr. Software Developer";
	private String position2 = "Sr. Financial Analyst";
	private String position3 = "cow";
	private String company1 = "Apple";
	private String company2 = "dunkin donuts";
	private String company3 = "J";
	private String companySize1 = "2";
	private String companySize2 = "73";
	private String companySize3 = "500,000";
	private String phoneNumber1 = "(201)256-7771";
	private String phoneNumber2 = "45";
	private String phoneNumber3 = "9732252898";
	private String profileUrl1 = "mary.bonanza@ralphlauren.com";
	private String profileUrl2 = "sirouhi.goldman@taj.com";
	private String profileUrl3 = "pineapple";
	private String numConnections1 = "200";
	private String numConnections2 = "2000";
	private String numConnections3 = "3";
	private String funding1 = "$5,000";
	private String funding2 = "10,000";
	private String funding3 = "$35";
	private String revenue1 = "$2,000";
	private String revenue2 = "10,000";
	private String revenue3 = "10000";
	private String department1 = "Software Engineering";
	private String department2 = "Business";
	private String department3 = "fitness"; 
	
	private static boolean isSupportedPlatform() {		
		Platform current = Platform.getCurrent();
		return Platform.MAC.is(current);
	}
	
	
	@Before
	public void createDriver() {
		if (isSupportedPlatform()){
			driver = new SafariDriver();
		}
				
		baseUrl = "https://fusemachines.com";
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		driver.manage().window().maximize();
		driver.manage().deleteAllCookies();
	}
	
	@Test
	public void testingtesting0() throws Exception{
	  driver.get(baseUrl + "/sales.ai/login");
	  driver.manage().deleteAllCookies();
	  driver.navigate().refresh();
	  driver.findElement(By.name("username")).clear();
	  driver.findElement(By.name("username")).sendKeys(adminUserName);
	  driver.findElement(By.name("password")).clear();
	  driver.findElement(By.name("password")).sendKeys(adminPassword);
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//section[@class='login-wrapper']/div/form/div[2]/span[2]/button")).click();
	  //Thread.sleep(2000);
	  //wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@class='navbar-left']/ul/li/a")));
	  //driver.findElement(By.xpath("//div[@class='navbar-left']/ul/li/a")).click();
	  Thread.sleep(2000);
	  //wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/a")));
	  driver.findElement(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/a")).click();
	  Thread.sleep(2000);
	  //wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/ul/li[2]/a[@href='/sales.ai/sourcing/upload']")));
	  driver.findElement(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/ul/li[2]/a[@href='/sales.ai/sourcing/upload']")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("//div[@class='ui search dropdown selection']/input[@class='search']")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']")).clear();
	  driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']")).sendKeys(sheetName);
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']")).sendKeys(Keys.RETURN);
	  //driver.findElement(By.xpath("//div[@class='ui search dropdown selection']/div[@class='menu transition visible']/div[@data-value='<fuseprospector-web@model:lead-generation/md-source::ember927:55cc9e52e4b036022fbd8ade>']")).click();
	  //driver.findElement(By.xpath("//div[@id='data-section']/div/div/div/div[@class='data-section-filters']/span/div/div[@class='menu transition visible']/div[2]")).click();
	  driver.findElement(By.id("file-field-withformat")).sendKeys("/Users/rtolpin/Downloads/Testing in fuseprospector (1).xlsx");
	  Thread.sleep(6000);
	  driver.findElement(By.className("upload-text")).click();
	  Thread.sleep(30000);
	  
	  /*Alert alert = driver.switchTo().alert();
	  alert.accept();*/
	  /*driver.findElement(By.xpath("//input[@placeholder='DB column 1']")).clear();
	  driver.findElement(By.xpath("//input[@placeholder='DB column 1']")).sendKeys("First Name");
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//input[@placeholder='DB column 2']")).clear();
	  driver.findElement(By.xpath("//input[@placeholder='DB column 2']")).sendKeys("Middle Name");
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//input[@placeholder='excel column 1']")).clear();
	  driver.findElement(By.xpath("//input[@placeholder='excel column 1']")).sendKeys("S no.");
	  Thread.sleep(1000);
	  driver.findElement(By.xpath("//input[@placeholder='excel column 2']")).clear();
	  driver.findElement(By.xpath("//input[@placeholder='excel column 2']")).sendKeys("LinkedInId");
	  driver.findElement(By.xpath("//div[@class='col-md-3']/form/button")).click();
	  Thread.sleep(2000);
	  driver.findElement(By.xpath("//div[@class='data-section-block']/div[3]/div[@class='col-md-3']/button")).click();*/
    }
	
	@Test
	public void testingtesting1() throws Exception{
		  driver.get(baseUrl + "/sales.ai");
		  Actions action = new Actions(driver);
		  driver.findElement(By.name("username")).clear();
		  driver.findElement(By.name("username")).sendKeys(adminUserName);
		  driver.findElement(By.name("password")).clear();
		  driver.findElement(By.name("password")).sendKeys(adminPassword);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//section[@class='login-wrapper']/div/form/div[2]/span[2]/button")).click();
		  Thread.sleep(1000);
		  //wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@class='navbar-left']/ul/li/a")));
		  driver.findElement(By.xpath("//div[@class='navbar-left']/ul/li/a")).click();
		  Thread.sleep(1000);
		  //wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/a")));
		  driver.findElement(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/a")).click();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@id='options-sidebar']/aside/ul/li[2]/ul/li/a[@href='/sales.ai/sourcing/clean']")).click();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='data-section-container']/div/i")).click();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ui search dropdown selection']/input[@class='search']")).click();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']")).clear();
		  driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']")).sendKeys("excel");
		  JavascriptExecutor js = null;
		  if (driver instanceof JavaScriptExecutor){
			  js = (JavascriptExecutor) driver;
		  }
		  WebElement element = driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']"));
		  String mouseOverScript = "if(document.createEvent){var evObj = document.createEvent('MouseEvents');evObj.initEvent('mouseover', true, false); arguments[0].dispatchEvent(evObj);} else if(document.createEventObject) { arguments[0].fireEvent('onmouseover');}";
		  js.executeScript(mouseOverScript, element);
		  
		  
		  driver.findElement(By.xpath("//div[@class='ui search dropdown selection active visible']/input[@class='search']")).sendKeys(Keys.RETURN);
		  /*Thread.sleep(6000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]/input")).sendKeys(email1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]/input")).sendKeys(email2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]/input")).sendKeys(email3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText7 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText75 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[1]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[1]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[1]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[1]/input")).sendKeys(firstName1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[1]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[3]/input")).sendKeys(email5);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText9 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[1]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[1]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[1]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[1]/input")).sendKeys(firstName2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[1]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[2]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[2]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[2]/input")).sendKeys(lastName1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[2]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText11= driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[2]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[2]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[2]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[2]/input")).sendKeys(lastName2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[2]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[4]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[4]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[4]/input")).sendKeys(position1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[4]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[4]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[4]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[4]/input")).sendKeys(position2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[4]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[4]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[4]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[4]/input")).sendKeys(position3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[4]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[5]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[5]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[5]/input")).sendKeys(company1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[5]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[5]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[5]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[5]/input")).sendKeys(company2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[5]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[5]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[5]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[5]/input")).sendKeys(company3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[5]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]/input")).sendKeys(email6);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[11]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[11]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[11]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[11]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[6]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[6]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[6]/input")).sendKeys(companySize1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[6]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[6]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[6]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[6]/input")).sendKeys(companySize2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[6]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[6]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[6]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[6]/input")).sendKeys(companySize3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[6]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText23 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[7]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[7]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[7]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[7]/input")).sendKeys(phoneNumber1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[7]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[7]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[7]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[7]/input")).sendKeys(phoneNumber2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[7]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[7]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[7]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[7]/input")).sendKeys(phoneNumber3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[7]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[8]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[8]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[8]/input")).sendKeys(profileUrl1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[8]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[8]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[8]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[8]/input")).sendKeys(profileUrl2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[8]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[8]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[8]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[8]/input")).sendKeys(profileUrl3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[8]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[9]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[9]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[9]/input")).sendKeys(numConnections1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[8]/td[9]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[9]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[9]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[9]/input")).sendKeys(numConnections2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[5]/td[9]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[9]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[9]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[9]/input")).sendKeys(numConnections3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[9]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[10]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[10]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[10]/input")).sendKeys(funding1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[7]/td[10]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]/input")).sendKeys(funding2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]/input")).sendKeys(funding3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[10]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[11]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[11]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[11]/input")).sendKeys(revenue1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[11]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[11]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[11]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[11]/input")).sendKeys(revenue2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[11]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[11]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[11]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[11]/input")).sendKeys(revenue3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[11]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[12]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[12]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[12]/input")).sendKeys(department1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[10]/td[12]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[12]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[12]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[12]/input")).sendKeys(department2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[12]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[12]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[12]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[12]/input")).sendKeys(department3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[6]/td[12]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(5000);
		  //Switch to page 2
		  driver.findElement(By.xpath("//div[@class='label-checker ui']/ul/li[3]/a")).click();
		  Thread.sleep(1000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[1]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[1]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[1]/input")).sendKeys(firstName1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[1]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[1]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[1]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[1]/input")).sendKeys(firstName2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[1]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]/input")).sendKeys(email4);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText43 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]/input")).sendKeys(email7);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[3]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]/input")).sendKeys(email3);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[4]/td[3]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText45 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[4]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[4]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[4]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[4]/input")).sendKeys(position1);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[1]/td[4]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  int lenText46 = driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[4]")).getText().length();
		  action.moveToElement(driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[4]")));
		  action.doubleClick();
		  action.click();
		  action.build().perform();
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[4]/input")).clear();
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[4]/input")).sendKeys(position2);
		  Thread.sleep(1000);
		  driver.findElement(By.xpath("//div[@class='ds-table table-responsive lead-table']/table/tbody/tr[2]/td[4]/input")).sendKeys(Keys.RETURN);
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//div[@class='label-checker ui']/ul/li[2]/a")).click();
		  Thread.sleep(3000);
		  driver.findElement(By.xpath("//div[@class='ui checkbox']")).click();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//div[@class='data-section-head']/div[@class='data-section-link-bar']/ul/li[2]/a")).click();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//div[@class='data-section-head']/div[@class='data-section-link-bar']/ul/li[3]/a")).click();
		  Thread.sleep(2000);
		  driver.findElement(By.xpath("//div[@class='navbar-right']/ul/li[2]/a")).click();
		  Thread.sleep(2000);*/
    }
	  
	
	@Test
	public void shouldBeAbleToPerformAGoogleSearch() {
		driver.get("http://www.google.com");
	    driver.findElement(By.name("q")).sendKeys("webdriver");
	    driver.findElement(By.name("btnG")).click();
	    new WebDriverWait(driver, 3)
	        .until(ExpectedConditions.titleIs("webdriver - Google Search"));
	    
	}
	
	
	@After
	public void tearDown() throws Exception {
		driver.quit();
		String verificationErrorString = verificationErrors.toString();
		if (!"".equals(verificationErrorString)) {
			fail(verificationErrorString);
		}
	}
	

}
